version: 2.1

orbs:
  terraform: circleci/terraform@3.1.0
  ruby: circleci/ruby@1.8.0

jobs:
  check_by_tflint:
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: tflint
          command: |
            cd lecture12/terraform/dev && tflint

workflows:
  deploy_infrastructure:
    jobs:
      - terraform/fmt:
          checkout: true
          context: terraform
          path: lecture12/terraform/dev
      - terraform/validate:
          checkout: true
          context: terraform
          path: lecture12/terraform/dev
          requires:
            - terraform/fmt
      - check_by_tflint:
          requires:
            - terraform/validate
      - terraform/plan:
          checkout: true
          context: terraform
          path: lecture12/terraform/dev
          persist-workspace: true
          requires:
            - check_by_tflint
      - terraform/apply:
          attach-workspace: true
          context: terraform
          path: lecture12/terraform/dev
          filters:
            branches:
              only: main
          requires:
            - terraform/plan
