version: 2.1

orbs:
  terraform: bjd2385/terraform@1.3.0


workflows:
  deploy_infrastructure:
    jobs:
      - terraform/fmt:
          checkout: true
          context: terraform
          path: lecture12/terraform/dev
      - terraform/validate:
          checkout: true
          context: terraform
          path: lecture12/terraform/dev
          requires:
            - terraform/fmt
      - terraform/tflint:
          checkout: true
          context: terraform
          path: lecture12/terraform/dev
          requires:
            - terraform/validate
      - terraform/plan:
          checkout: true
          context: terraform
          path: lecture12/terraform/dev
          persist-workspace: true
          requires:
            - terraform/tflint
      - terraform/apply:
          attach-workspace: true
          context: terraform
          path: lecture12/terraform/dev
          filters:
            branches:
              only: main
          requires:
            - terraform/plan
