version: 2.1

orbs:
  terraform: circleci/terraform@3.1.0
  terraform-tflint: hqo/terraform@1.0.3
  ruby: circleci/ruby@1.8.0

workflows:
  deploy_infrastructure:
    jobs:
      - terraform/fmt:
          checkout: true
          context: terraform
          path: lecture12/terraform/dev
      - terraform/validate:
          checkout: true
          context: terraform
          path: lecture12/terraform/dev
          requires:
            - terraform/fmt
      - terraform-tflint/tflint
      - terraform/plan:
          checkout: true
          context: terraform
          path: lecture12/terraform/dev
          persist-workspace: true
          requires:
            - terraform/validate
      - terraform/apply:
          attach-workspace: true
          context: terraform
          path: lecture12/terraform/dev
          filters:
            branches:
              only: main
          requires:
            - terraform/plan
