version: 2.1

orbs:
  terraform: circleci/terraform@3.1.0
  terraform-tflint: hqo/terraform@1.0.3
  ansible-playbook: orbss/ansible-playbook@0.0.5
  ruby: circleci/ruby@1.8.0

commands:
  install-tflint:
    description: "Install TFLint"
    steps:
      - run:
          command: wget -P /tmp https://github.com/terraform-linters/tflint/releases/download/v0.38.1/tflint_linux_amd64.zip && unzip /tmp/tflint_linux_amd64.zip -d /usr/local/bin

jobs:
  check_by_tflint:
    executor: terraform/default
    steps:
      - checkout
      - install-tflint
      - run:
          name: tflint
          command: |
            cd lecture12/terraform/dev && terraform init
            tflint --init && tflint
  ansible:
    executor: ansible-playbook/default
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - b5:a8:cb:13:7d:b6:19:9b:5f:53:e4:e8:ca:75:41:e4
      - ansible-playbook/playbook:
          playbook: lecture12/ansible/playbook.yml
          playbook-options: "-u ec2-user -i lecture12/ansible/inventory --private-key ~/.ssh/udemysample.pem"

workflows:
  deploy_infrastructure:
    jobs:
      - terraform/fmt:
          checkout: true
          context: terraform
          path: lecture12/terraform/dev
      - terraform/validate:
          checkout: true
          context: terraform
          path: lecture12/terraform/dev
          requires:
            - terraform/fmt
      - check_by_tflint:
          requires:
            - terraform/validate
      - terraform/plan:
          checkout: true
          context: terraform
          path: lecture12/terraform/dev
          persist-workspace: true
          requires:
            - check_by_tflint
      - terraform/apply:
          attach-workspace: true
          context: terraform
          path: lecture12/terraform/dev
          filters:
            branches:
              only: main
          requires:
            - terraform/plan
      - ansible:
          requires:
            - terraform/apply
